'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5420.
'
Namespace WSRFID
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebService1Soap", [Namespace]:="http://WebService_tse_RFID/")>  _
    Partial Public Class WebService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost:50633/WS_RFID.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/HelloWorld", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginHelloWorld(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("HelloWorld", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndHelloWorld(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/ComprobarUsuario", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobarUsuario(ByVal id_user As Integer) As String
            Dim results() As Object = Me.Invoke("ComprobarUsuario", New Object() {id_user})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginComprobarUsuario(ByVal id_user As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ComprobarUsuario", New Object() {id_user}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndComprobarUsuario(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/CajasDeSede", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CajasDeSede(ByVal id_sede As Integer, ByVal id_paquete As Integer) As Integer
            Dim results() As Object = Me.Invoke("CajasDeSede", New Object() {id_sede, id_paquete})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCajasDeSede(ByVal id_sede As Integer, ByVal id_paquete As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CajasDeSede", New Object() {id_sede, id_paquete}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCajasDeSede(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/ComprobarRFID", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobarRFID(ByVal rfid As String) As String
            Dim results() As Object = Me.Invoke("ComprobarRFID", New Object() {rfid})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginComprobarRFID(ByVal rfid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ComprobarRFID", New Object() {rfid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndComprobarRFID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/sedeLogistica", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function sedeLogistica() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("sedeLogistica", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginsedeLogistica(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("sedeLogistica", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndsedeLogistica(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
