'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5420.
'
Namespace WS_RFID
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebService1Soap", [Namespace]:="http://WebService_tse_RFID/")>  _
    Partial Public Class WebService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://172.16.1.226:8091/WS_RFID.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/comprobar_sede", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function comprobar_sede(ByVal id_ruta As Integer) As Integer
            Dim results() As Object = Me.Invoke("comprobar_sede", New Object() {id_ruta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Begincomprobar_sede(ByVal id_ruta As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("comprobar_sede", New Object() {id_ruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endcomprobar_sede(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/CajasListasDespacho", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CajasListasDespacho(ByVal id_ruta As Integer) As Integer
            Dim results() As Object = Me.Invoke("CajasListasDespacho", New Object() {id_ruta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCajasListasDespacho(ByVal id_ruta As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CajasListasDespacho", New Object() {id_ruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCajasListasDespacho(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/ComprobarRFID", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobarRFID(ByVal rfid As String) As Integer
            Dim results() As Object = Me.Invoke("ComprobarRFID", New Object() {rfid})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginComprobarRFID(ByVal rfid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ComprobarRFID", New Object() {rfid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndComprobarRFID(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/Caja_pertenezca_sede", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Caja_pertenezca_sede(ByVal id_caja As Integer, ByVal id_ruta As Integer) As Integer
            Dim results() As Object = Me.Invoke("Caja_pertenezca_sede", New Object() {id_caja, id_ruta})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCaja_pertenezca_sede(ByVal id_caja As Integer, ByVal id_ruta As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Caja_pertenezca_sede", New Object() {id_caja, id_ruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCaja_pertenezca_sede(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/comprobar_caja_completa", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function comprobar_caja_completa(ByVal id_caja As Integer) As Integer
            Dim results() As Object = Me.Invoke("comprobar_caja_completa", New Object() {id_caja})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function Begincomprobar_caja_completa(ByVal id_caja As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("comprobar_caja_completa", New Object() {id_caja}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endcomprobar_caja_completa(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/actualizar_caja", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub actualizar_caja(ByVal id_caja As Integer)
            Me.Invoke("actualizar_caja", New Object() {id_caja})
        End Sub
        
        '''<remarks/>
        Public Function Beginactualizar_caja(ByVal id_caja As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("actualizar_caja", New Object() {id_caja}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub Endactualizar_caja(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/actualizar_caja_inconsistente", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub actualizar_caja_inconsistente(ByVal id_caja As Integer, ByVal id_ruta As Integer)
            Me.Invoke("actualizar_caja_inconsistente", New Object() {id_caja, id_ruta})
        End Sub
        
        '''<remarks/>
        Public Function Beginactualizar_caja_inconsistente(ByVal id_caja As Integer, ByVal id_ruta As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("actualizar_caja_inconsistente", New Object() {id_caja, id_ruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub Endactualizar_caja_inconsistente(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/HelloWorld", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginHelloWorld(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("HelloWorld", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndHelloWorld(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebService_tse_RFID/ComprobarUsuario", RequestNamespace:="http://WebService_tse_RFID/", ResponseNamespace:="http://WebService_tse_RFID/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobarUsuario(ByVal nombre As String, ByVal password As String) As Integer
            Dim results() As Object = Me.Invoke("ComprobarUsuario", New Object() {nombre, password})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginComprobarUsuario(ByVal nombre As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ComprobarUsuario", New Object() {nombre, password}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndComprobarUsuario(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
End Namespace
